# MongoDB
spring.data.mongodb.uri=mongodb+srv://ankushsharma2006:qh4UBCXgK91drmcF@cloudshare.g64rnkh.mongodb.net/cloudshare?retryWrites=true&w=majority&appName=CloudShare

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server.servlet.context-path=/api/v1.0

# JWT
jwt.secret=QaRzNgHGmuld0RNnQ03F/VlZ5pCR3V9cyXyCrhavo2x2ae0SLF8gnTks37Gh9TVtV/YPG5I5qj9bGhKUwzKFvQ==
jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=604800000

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

razorpay.key.id=rzp_test_TNAz5yN4CUSJDo
razorpay.key.secret=5c6GtjN3SFt5cYkwckCs8tQo

server.port=${PORT:8080}

cloudinary.cloud-name=dtd8pa6yn
cloudinary.api-key=148155411521496
cloudinary.api-secret=VOqfbvcqo_pjYWEyvhZzH7Nw3KI

gemini.api.key=AQ.Ab8RN6L4DpTLzHeNZyzYjrQBlc_WnVYLn2PXkZLr2hJ97FY1Mw
gemini.embedding.model=gemini-embedding-001
gemini.generation.model=gemini-2.5-flash